language: ruby
script:
    - bundle exec jekyll build
    - bundle exec htmlproofer ./_site --disable-external --allow-hash-href
env:
      global:
            - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
